# Generated by Django 5.2.10 on 2026-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='join_date',
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(default='2026-01-31'),
            preserve_default=False,
        ),
    ]
